<?php

declare(strict_types = 1);

/**
 * Humanids
 * Human-readable identifier generation
 * @author  biohzrdmx <github.com/biohzrdmx>
 * @license MIT
 */

namespace Humanids\Tokens;

class AdverbToken extends AbstractWordToken {

    /**
     * @inheritdoc
     */
    protected array $words = [
        'accidentally',
        'achingly',
        'angrily',
        'annoyingly',
        'anxiously',
        'audibly',
        'awkwardly',
        'badly',
        'blindly',
        'boastfully',
        'boldly',
        'bravely',
        'brightly',
        'briskly',
        'casually',
        'cheerfully',
        'coyly',
        'crazily',
        'cruelly',
        'defiantly',
        'deftly',
        'dejectedly',
        'deliberately',
        'devotedly',
        'doubtfully',
        'dramatically',
        'dutifully',
        'eagerly',
        'elegantly',
        'emphatically',
        'enormously',
        'enviously',
        'excitedly',
        'faintly',
        'faithfully',
        'fleetingly',
        'foolishly',
        'fortunately',
        'gleefully',
        'gracefully',
        'gradually',
        'haltingly',
        'happily',
        'hastily',
        'honestly',
        'hopelessly',
        'hungrily',
        'hurriedly',
        'immediately',
        'inaudibly',
        'innocently',
        'instantly',
        'irritably',
        'jealously',
        'joylessly',
        'kindly',
        'languidly',
        'lazily',
        'leisurely',
        'loudly',
        'madly',
        'merrily',
        'miserably',
        'morosely',
        'mortally',
        'nervously',
        'noisily',
        'obediently',
        'obnoxiously',
        'painfully',
        'perfectly',
        'politely',
        'poorly',
        'powerfully',
        'promptly',
        'quickly',
        'quietly',
        'rapidly',
        'rudely',
        'sadly',
        'safely',
        'selfishly',
        'seriously',
        'shakily',
        'shrilly',
        'silently',
        'slowly',
        'softly',
        'solemnly',
        'speedily',
        'sternly',
        'swiftly',
        'tediously',
        'terribly',
        'unexpectedly',
        'unhappily',
        'warmly',
        'weakly',
        'wearily',
        'wildly',
    ];
}
